import { css } from 'lit-element';
export default css `html,body{font-family:"proxima-nova",sans-serif;font-size:14px;line-height:1.5rem}a{background-color:transparent;color:#0A57A1}h1,h2,h3,h4,h5,h6{margin-top:16px;margin-bottom:10px;font-weight:600;line-height:1.5rem}h1{margin-top:20px;font-size:1.5rem}h2{margin-top:18px;font-size:1.25rem}h3{font-size:1.125rem}h4{font-size:1rem}h5{font-size:.875rem}h6{font-size:.75rem}small{font-size:75%}sub,sup{position:relative;font-size:75%;line-height:0;vertical-align:baseline}sup{top:-0.5em}sub{bottom:-0.25em}:host{--rating-bar-font-family: proxima-nova,sans-serif;--rating-bar-font-weight: 600;--rating-bar-label-color: #242C38;--rating-bar-background-color: #E1E6ED;--rating-bar-donut-track-stroke-color: #E1E6ED;--rating-bar-donut-margin: 8px;--rating-bat-linear-padding: 8px;--rating-bar-excellent: #238738;--rating-bar-great: #67AB04;--rating-bar-average: #D99B22;--rating-bar-poor: #D97322;--rating-bar-bad: #D9222A}/*!
To Render a Donut Bar we consume svg's <circle> element consists of following properties which are calculated as follows
for width = 40px , height = 40px , viewbox = 0 0 40 40
stroke-width : 1/10th the total width of our circle i.e 4.
r (radius) : radius is calculated using ((width / 2) - (stroke-width / 2)) i.e 18
the cx and cy attributes are the x & y coordinates for the center of the circle which are half of that of width and height i.e cx=20 cy=20
stroke-dasharray : the circumference of the circle is calculated using 2πr : 2 * 3.14 * r : 113.34 
stroke-dashoffset : To show the progress on the circle we fill the donut track using expression :  
circumference * (1 - (progress / 100))
eg : for displaying 60% progress
113.34 * (1 - (60 / 100))
*/:host([type='linear']){display:block;width:100%}:host([type='donut']){align-items:center;display:inline-flex;justify-content:center;width:40px}:host([type='donut']) .donut-track__info{position:absolute}.linear-track{background-color:var(--rating-bar-background-color);border-radius:25px;width:100%}.linear-track .linear-track__indicator{border-radius:25px;height:8px;margin-bottom:var(--rating-bat-linear-padding)}.linear-track .linear-track__indicator.linear-track--excellent{background-color:var(--rating-bar-excellent)}.linear-track .linear-track__indicator.linear-track--great{background-color:var(--rating-bar-great)}.linear-track .linear-track__indicator.linear-track--average{background-color:var(--rating-bar-average)}.linear-track .linear-track__indicator.linear-track--poor{background-color:var(--rating-bar-poor)}.linear-track .linear-track__indicator.linear-track--bad{background-color:var(--rating-bar-bad)}.linear-track__info{color:var(--rating-bar-label-color);font-family:var(--rating-bar-font-family);font-weight:var(--rating-bar-font-weight);display:flex;justify-content:space-between;font-size:1.6rem}.donut-track__info{color:var(--rating-bar-label-color);font-family:var(--rating-bar-font-family);font-weight:var(--rating-bar-font-weight);font-size:1.4rem}.donut{position:relative;transform:rotate(-90deg)}.donut .donut-track{stroke:var(--rating-bar-donut-track-stroke-color);fill:none;stroke-width:4}.donut .donut-track__indicator{fill:none;stroke-width:4;stroke-dasharray:113.04}.donut .donut-track__indicator.donut-track--excellent{stroke:var(--rating-bar-excellent)}.donut .donut-track__indicator.donut-track--great{stroke:var(--rating-bar-great)}.donut .donut-track__indicator.donut-track--average{stroke:var(--rating-bar-average)}.donut .donut-track__indicator.donut-track--poor{stroke:var(--rating-bar-poor)}.donut .donut-track__indicator.donut-track--bad{stroke:var(--rating-bar-bad)}`;
